-- TP5 optionnel requêtes avancées

--a
SELECT * FROM ARTICLE ORDER BY DESIGNATION;

--b
SELECT * FROM ARTICLE ORDER BY PRIX DESC;

--c
SELECT * FROM ARTICLE A WHERE A.DESIGNATION LIKE 'Boulon%' ORDER BY PRIX ASC;

--d
SELECT * FROM ARTICLE A WHERE A.DESIGNATION LIKE '%sachet%';

--e
SELECT * FROM ARTICLE A WHERE A.DESIGNATION LIKE '%Sachet%';

--f
SELECT A.*, F.NOM FROM ARTICLE A, FOURNISSEUR F WHERE A.ID_FOU = F.ID ORDER BY F.NOM ASC AND A.PRIX DESC;

--g
SELECT * FROM ARTICLE A INNER JOIN FOURNISSEUR F ON A.ID_FOU = F.ID AND A.ID_FOU = 3;

--h
SELECT A.ID_FOU, AVG(A.PRIX) FROM ARTICLE A, FOURNISSEUR F WHERE A.ID_FOU = F.ID AND A.ID_FOU = 3 GROUP BY A.ID_FOU;

--i
SELECT A.ID_FOU, AVG(A.PRIX) FROM ARTICLE A, FOURNISSEUR F WHERE A.ID_FOU = F.ID GROUP BY A.ID_FOU;

--j
SELECT * FROM BON B WHERE B.DATE_COMMANDE BETWEEN ('2019-03-01 12:00:00') AND ('2019-04-05 12:00:00');

--k
SELECT * FROM BON B INNER JOIN COMPO C INNER JOIN ARTICLE A ON C.ID_BON = B.ID AND C.ID_ART = A.ID AND A.DESIGNATION LIKE 'Boulon%';

--l
SELECT * FROM BON B INNER JOIN COMPO C INNER JOIN ARTICLE A INNER JOIN FOURNISSEUR F ON C.ID_BON = B.ID AND C.ID_ART = A.ID AND A.ID_FOU = F.ID AND A.DESIGNATION LIKE 'BOULON%';

--m
SELECT C.ID_BON, SUM(A.PRIX * C.QTE) FROM BON B, COMPO C, ARTICLE A WHERE B.ID = C.ID_BON AND C.ID_ART = A.ID GROUP BY C.ID_BON;

--n
SELECT C.ID_BON, COUNT(C.QTE) FROM BON B, COMPO C, ARTICLE A WHERE B.ID = C.ID_BON AND C.ID_ART = A.ID GROUP BY C.ID_BON;

--o
SELECT B.NUMERO, COUNT(C.QTE) FROM BON B JOIN COMPO C ON B.ID = C.ID_BON GROUP BY B.NUMERO HAVING COUNT(C.QTE) >= 25;

--p
SELECT B.ID, SUM(A.PRIX * C.QTE) FROM BON B, COMPO C, ARTICLE A WHERE B.ID = C.ID_BON AND C.ID_ART = A.ID AND B.DATE_COMMANDE LIKE '%04%';



