-- TP2

CREATE TABLE ARTICLE (
    ID INT PRIMARY KEY,
    REF VARCHAR(120),
    DESIGNATION VARCHAR(120),
    PRIX DECIMAL(5,2),
    ID_FOU INT FOREIGN KEY
);

CREATE TABLE FOURNISSEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR(120)
);

CREATE TABLE BON (
    ID INT PRIMARY KEY,
    NUMERO VARCHAR(120),
    DATE_COMMANDE DATE,
    DELAI INT, -- TIME
    ID_FOU INT FOREIGN KEY
);

CREATE TABLE COMPO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QTE INT,
    ID_ART INT FOREIGN KEY,
    ID_BON INT FOREIGN KEY
);

ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLE_1 FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE BON ADD CONSTRAINT FK_BON_1 FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE COMPO ADD CONSTRAINT FK_ARTICLE_2 FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);
ALTER TABLE COMPO ADD CONSTRAINT FK_BON_2 FOREIGN KEY (ID_BON) REFERENCES BON(ID);

