-- TP4

--a
SELECT * FROM ARTICLE;

--b
SELECT * FROM ARTICLE A WHERE A.PRIX >= 2;

--c
SELECT * FROM ARTICLE A WHERE A.PRIX >= 2 AND A.PRIX <= 6.25;

--d
SELECT * FROM ARTICLE A WHERE A.PRIX BETWEEN 2 AND 6.25;

--e
SELECT * FROM ARTICLE A WHERE A.PRIX NOT BETWEEN 2 AND 6.25;

--f
SELECT * FROM ARTICLE A WHERE A.ID_FOU = 1 OR A.ID_FOU = 3;

--g
SELECT * FROM ARTICLE A WHERE A.ID_FOU IN (1, 3);

--h
SELECT * FROM ARTICLE A WHERE A.ID_FOU NOT IN (1, 3);

--i
SELECT * FROM BON B WHERE B.DATE_COMMANDE BETWEEN '2019-02-01' AND '2019-04-30';